leftnav:
- identifier: 7542686e-78cc-a196-d629-ebeef23a6016
  name: Syllabus
  url: /pages/syllabus
  weight: 10
- identifier: 8aab2a86-7ebb-d4c0-9856-bf6fa01a4537
  name: Calendar
  url: /pages/calendar
  weight: 20
- identifier: f6c1a3aa-e18e-775d-4825-096da39a5e80
  name: Lecture Notes
  url: /pages/lecture-notes
  weight: 30
- identifier: 4f132748-1a5d-695f-b670-ff459908e75b
  name: Assignments
  url: /pages/assignments
  weight: 40
- identifier: 01120f78-9477-cd7e-5075-23f35874c938
  name: Projects
  url: /pages/projects
  weight: 50
- identifier: 3c5bbbd7-4857-7e7d-002b-0746f9660f09
  name: Readings
  url: /pages/readings
  weight: 60
